# apiVersion: v1
# kind: ConfigMap
# metadata:
#  name: terraform-simulation-app-config
#  namespace: development

apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: default
data:
 index.html: |
   <html>
   <head><title>Hello from Argo</title></head>
   <body>
   <h1>Hello from Argo updated again II</h1>
   </body>
   </html>