# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: terraform-simulation-app-deployment
#   namespace: development
#   labels:
#     app: terraform-simulation-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: terraform-simulation-app
#   template:
#     metadata:
#       labels:
#         app: terraform-simulation-app
#     spec:
#       containers:
#       - name: terraform-simulation-app
#         image: amtrbouaro/terraform-simulation-app:latest
#         ports:
#         - containerPort: 3001
#         volumeMounts:
#         - name: terraform-simulation-app-config-volume
#           mountPath: /usr/share/app/
#       volumes:
#       - name: terraform-simulation-app-config-volume
#         configMap:
#          name: terraform-simulation-app-config

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:latest
       ports:
       - containerPort: 80
       volumeMounts:
       - name: nginx-config-volume
         mountPath: /usr/share/nginx/html
     volumes:
     - name: nginx-config-volume
       configMap:
         name: nginx-config